#!/bin/bash

# fzf init
if command -v fzf &> /dev/null; then
  if [[ -f /usr/share/fzf/completion.bash ]]; then
    source /usr/share/fzf/completion.bash
  fi
  if [[ -f /usr/share/fzf/key-bindings.bash ]]; then
    source /usr/share/fzf/key-bindings.bash
  fi
fi

# Zoxide Init
if command -v zoxide &> /dev/null; then
  eval "$(zoxide init bash)"
  alias cd='zd'
  alias cdi='zi'
fi

# Starship init
if command -v starship &> /dev/null; then
  eval "$(starship init bash)"
fi

# BatCat init
if command -v batcat &> /dev/null; then
  alias cat='batcat -p'
fi
if command -v bat &> /dev/null; then
  alias cat='bat -p'
fi
