#!/bin/bash
# This file is for kafka development

if [[ -v KAFKA_BASE ]]; then
    export PATH=$PATH:${KAFKA_BASE}/bin
    export PATH=$PATH:${KAFKA_BASE}/scripts
    export KAFKA_OPTS="-Djava.security.auth.login.config=${KAFKA_BASE}/config/admin_jaas.conf"
fi


