#!/bin/bash
source ~/Bash-Configuration/bash/aliases
source ~/Bash-Configuration/bash/env
source ~/Bash-Configuration/bash/installs
source ~/Bash-Configuration/bash/kafka_env
source ~/Bash-Configuration/bash/aliases
